export default class SymbolGetter {
  // THIS IS A MASSIVE HORRIBLE CASE STATEMENT that comes from the correspondence between
  // alchemical symbols and chemical properties. the letters are the thing you use to get
  // the right symbol in the Alchemy font
  // TODO: move to spreadsheet
  public static getSymbolForProperty(propertyName: string): string {
    switch (propertyName) {
      case 'healing':
        return 'q';
      case 'damage' :
        return 'c';
      case 'inversion':
        return 'f';
      case 'stillness':
        return 's';
      case 'disease':
        return 'S';
      case 'toxicity':
        return 'H';
      case 'fire':
        return 'Y';
      case 'ice':
        return '~';
      case 'earth':
        return '=';
      case 'air':
        return 'r';
      case 'weaken':
        return '*';
      case 'adhesive':
        return 'x';
      case 'permanence':
        return 'O';
      case 'persistence':
        return 'e';
      case 'erosion':
        return 'D';
      case 'knowledge':
        return 'k';
      case 'stability':
        return 'C';
      case 'frailty':
        return '!';
      case 'rebirth':
        return 'P';
      case 'creation':
        return 'E';
      case 'unraveling':
        return 'K';
      case 'body':
        return 'Q';
      case 'pain':
        return 'l';
      case 'insidious':
        return 'm';
      case 'water':
        return 'g';
      case 'lightning':
        return 'n';
      case 'quintessence':
        return '[';
      case 'slowness':
        return 'u';
      case 'speed':
        return 'W';
      case 'devastation':
        return 'V';
      case 'agitation':
        return 'v';
      case 'confusion':
        return '-';
      case 'calm':
        return '?';
      case 'stealth':
        return ',';
      case 'alertness':
        return '7';
      case 'decay':
        return 'Z';
      case 'transformation':
        return '%';
      case 'oblivion':
        return 'M';
      case 'leaching':
        return '<';
      case 'vine':
        return 'U';
      case 'acid':
        return '/';
      case 'fortify':
        return 'L';
      case 'purification':
        return '@';
      case 'storing energy':
        return 'j';
      case 'sorrow':
        return 'i';
      case 'blood':
        return 'R';
      case 'emotion':
        return 'd';
      case 'animal':
        return '&';
      case 'cooperation':
        return 'o';
      case 'spirit':
        return 't';
      case 'fear':
        return 'h';
      case 'resilience':
        return 'A';
      case 'memory':
        return 'z';
      case 'curse':
        return 'N';
      case 'mimic':
        return ']';
      case 'time':
        return '{';
      case 'will':
        return '>';
      case 'repetition':
        return 'G';
      case 'lethargy':
        return 'w';
      case 'visions':
        return 'F';
      case 'transference':
        return 'a';
      case 'balance':
        return ';';
      case 'stasis':
        return 'b';
      case 'entropy':
        return 'p';
      case 'shadows':
        return 'J';
      case 'famine':
        return '}';
      case 'undeath':
        return '\\';
      case 'lethality':
        return 'I';
      case 'courage':
        return 'y';
      case 'communication':
        return '.';
      case 'protection':
        return 'B';
      default:
        return '';
    }
  }
}
